### PR TITLE
Small fixes

### LINKED ISSUE #38: Truncated text in SunView
simulator screen shot dec 21 2016 9 18 17 am

### PR DESCRIPTION
**Pull request by marijnschilling**
Fixes #38 & #39

### CODE REVIEW

File: iOS/Source/InformationController.swift [hunk 1]
```diff
@@ -9,6 +9,13 @@ class InformationController: UIViewController {
 
     var messageLabelHeightAnchor: NSLayoutConstraint?
 
+    lazy var webButton: UIButton = {
+        let button = UIButton(withAutoLayout: true)
+        button.addTarget(self, action: #selector(didClickWebButton), for: .touchUpInside)
```
Comment (3lvis) [inline iOS/Source/InformationController.swift]: Can we have `didSelectLinkButton` instead? Having anything called click in iOS doesn't feel right.

File: iOS/Source/SunView.swift [hunk 2]
```diff
@@ -102,13 +102,15 @@ class SunView: UIView {
     override func layoutSubviews() {
         super.layoutSubviews()
 
+        let labelWidth = CGFloat(35.0)
+
         // TODO: check if the view layout is also possible using constraints
-        self.sunriseLabel.frame = CGRect(x: 0, y: 108, width: 33, height: 16)
-        self.sunsetLabel.frame = CGRect(x: self.bounds.width - 33, y: 108, width: 33, height: 16)
+        self.sunriseLabel.frame = CGRect(x: 0, y: 108, width: labelWidth, height: 16)
```
Comment (3lvis) [inline iOS/Source/SunView.swift]: 💥

**Comment by marijnschilling** [comment]
🚢?
